# Generated by Django 5.0.3 on 2024-05-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_pet_adoption_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='free',
            new_name='fee',
        ),
    ]
