# Generated by Django 5.0.3 on 2024-05-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_rename_free_pet_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('wishlist', 'Wishlist'), ('adopted', 'Adopted')], default='available', max_length=20),
        ),
    ]
