# Generated by Django 5.0.3 on 2024-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rating',
            field=models.FloatField(choices=[(0, 0), (0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], default=0),
        ),
    ]
