# Generated by Django 5.0.3 on 2024-05-23 05:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_adoptionrequest_status'),
        ('pet', '0004_alter_pet_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('pet', 'adopter')},
        ),
    ]
